package exception;

class Main{
        public static void main(String args[]){
try
        {
        int a, b;
        b = 0;
        a = 5 / b;
        System.out.print("B");}
        catch(ArithmeticException e){

        System.out.print("A");


    }}}